name: Rotel Card
description: 🔊 Rotel Remote Card
type: lovelace
keywords:
  - rotelcard
  - rotel
  - rotel
  - rotel
  - television
author:
  name: mar_robHD
license: Apache License, Version 2.0
files:
  - rotel-card.js
  - rotel-card-editor.js
